kind: Endpoints
apiVersion: v1
metadata:
  name: heimdall-server
subsets:
  - addresses:
      - ip: 192.168.20.5
    ports:
      - port: 9090
        name: http
---
kind: Service
apiVersion: v1
metadata:
  name: heimdall-server
spec:
  ports:
    - protocol: TCP
      name: http
      port: 443
      targetPort: 9090
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: heimdall-server
spec:
  rules:
  - host: heimdall.jtcressy.net
    http:
      paths:
      - backend:
          serviceName: heimdall-server
          servicePort: http