kind: StorageClass
apiVersion: storage.k8s.io/v1beta1
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: true
  name: fast
provisioner: kubernetes.io/vsphere-volume
parameters:
  diskformat: thin