apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    volume.beta.kubernetes.io/storage-class: managed-nfs-storage
  name: ghost-data
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
status: {}