apiVersion: v1
kind: Pod
metadata:
  name: ssh-ghost
  labels:
    app: ssh-ghost
spec:
  containers:
  - image: krlmlr/debian-ssh
    name: ssh-ghost-container
    env:
    - name: SSH_KEY
      value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC1BoMF9lpcaRxkvrAHWlWDaFAcLy2TDT/IOBmwPM4lh5dMbZX76nZjKcQbU144kYdfAVEQG0mwhwdljDDvFvJVnSwZqYP7aep4Tx9YYbmDpwutj3cbN6x3DXOiggroqO8SXjokzinSUGZCF3G0YOY+BarIrHC4tgY8gDm2tdRdVPWvlZ/H+6XnpEy3yXEYT2wCdnwohaZVzCackylEd8Me9vbLqVsS5vo6o2XWba1Inpjig2BAMlL9TRDWvRZ3Nv5VM+DDGXdftST9j0sHWM6Sdfen+3gsVPL8ZmwFlETLziIb11oEL0DXGyUQ+2HGR58ArCMHdTmT0fkvp1aERcOl jtcressy@heimdall.jtcressy.net"
    ports:
    - containerPort: 22
      name: ssh
    volumeMounts:
    - mountPath: /ghost
      name: ghost-persistent-storage
  volumes:
    - name: ghost-persistent-storage
      persistentVolumeClaim:
        claimName: ghost-data
---
apiVersion: v1
kind: Service
metadata:
  name: ssh-ghost-service
spec:
  selector:
    app: ssh-ghost
  ports:
  - name: ssh
    port: 22
    targetPort: 22
  type: NodePort